name: humidy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter: 
    sdk: flutter
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  http: ^1.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: ^2.1.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - Images/


  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.ttf
        - asset: fonts/Schyler-Italic.ttf
          style: italic
    - family: Trajan Pro
      fonts:
        - asset: fonts/TrajanPro.ttf
        - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
  